export const dogsTypes = {
  GET_ALL_DOGS: "GET_ALL_DOGS",
  GET_ALL_DOGS_SUCCESFULL: "GET_ALL_DOGS_SUCCESFULL",
  GET_ALL_DOGS_ERROR: "GET_ALL_DOGS_ERROR",

  GET_DOG_BY_ID: "GET_DOG_BY_ID",
  GET_DOG_BY_ID_SUCCESFULL: "GET_DOG_BY_ID_SUCCESFULL",
  GET_DOG_BY_ID_ERROR: "GET_DOG_BY_ID_ERROR",
};
export const activitiesTypes = {
  GET_ALL_ACTIVITIES: "GET_ALL_ACTIVITIES",
  GET_ALL_ACTIVITIES_SUCCESFULL: "GET_ALL_ACTIVITIES_SUCCESFULL",
  GET_ALL_ACTIVITIES_ERROR: "GET_ALL_ACTIVITIES_ERROR",

  GET_ACTIVITY_BY_ID: "GET_ACTIVITY_BY_ID",
  GET_ACTIVITY_BY_ID_SUCCESFULL: "GET_ACTIVITY_BY_ID_SUCCESFULL",
  GET_ACTIVITY_BY_ID_ERROR: "GET_ACTIVITY_BY_ID_ERROR",
};
