export const dogsTypes = {
    GET_ALL_DOGS: "GET_ALL_DOGS",
    GET_ALL_DOGS_SUCCESFULL: "GET_ALL_DOGS_SUCCESFULL",
    GET_ALL_DOGS_ERROR: "GET_ALL_DOGS_ERROR",
  
    GET_DOG_BY_ID: "GET_DOG_BY_ID",
    GET_DOG_BY_ID_SUCCESFULL: "GET_DOG_BY_ID_SUCCESFULL",
    GET_DOG_BY_ID_ERROR: "GET_DOG_BY_ID_ERROR",
};
